name: pylama test
on: [push]
  secrets:
    GH_TOKEN:
      required: true
env:
  PYLAMA_VERSION: 7.7.1
jobs:
  dash-pylama:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - name: Set up files
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: install pylama
        run: |
          pip3 install pylama==${{env.PYLAMA_VERSION}}
      - name: run pylama
        run: |
          pylama .