name: Actions Workflow 

on: [push]
env:
  PYLAMA_VERSION: 7.7.1
  PYFLAKES_VERSION: 2.4.0

jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - name: List Files 
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout 
        uses: kalanatd/github-actions-reusable-workflows/.github/workflows/checkout-action.yaml@main
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: install pyflakes
        run: |
          pip3 install pyflakes==${{env.PYFLAKES_VERSION}}
          pyflakes --version
      - name: install pylama
        run: |
          pip3 install pylama==${{env.PYLAMA_VERSION}}
          pylama --version
      - name: bash
        run: |
          ls -al